import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_KEY, GUEST } from './config.js';

const sb = createClient(SUPABASE_URL, SUPABASE_KEY);
const app = document.querySelector('#app');
async function ensureGuest(){
  if(!GUEST)return;
  const {data:{session}}=await sb.auth.getSession();
  if(session?.user)return session.user;
  const {data,error}=await sb.auth.signInAnonymously();
  if(error)throw new Error('Guest session could not be created: '+error.message);
  return data?.user||null;
}
const topics = [
  ['Forces and motion','Motion, forces, momentum and pressure'],
  ['Energy','Energy stores, transfers, work, power and efficiency'],
  ['Thermal physics','Particle model, temperature, heating and cooling'],
  ['Waves','Wave properties, sound, light and electromagnetic waves'],
  ['Electricity','Circuits, current, voltage, resistance and electrical power'],
  ['Magnetism','Magnetic fields, motors, generators and transformers'],
  ['Radioactivity','Atomic structure, radiation, decay and safety'],
  ['Space physics','Earth, satellites, stars and the wider universe']
];
let state={page:'home',topic:0,result:null};

function header(){return '<header class="topbar"><button class="brand" style="border:0;background:none;padding:0" data-page="home">Physics AI-sistant</button><div class="header-right"><div class="model-chip"><span class="model-dot"></span><span>Physics AI-sistant</span><small>IGCSE Physics</small></div><div class="status"><i class="dot"></i> Workspace</div></div></header>'}
function shell(content){app.innerHTML='<div class="shell">'+header()+content+'</div>';bind()}
function home(){shell('<main class="wrap"><section class="hero"><div class="eyebrow">IGCSE Physics workspace</div><h1>Choose what you want to do.</h1><p>No clutter. Pick a Physics task and go straight into the work.</p></section><section class="choices"><button class="choice" data-page="topic"><span class="num">01</span><div class="icon">â</div><h2>Full Classified Topic Checker</h2><p>Choose a topic and subtopic, practise questions, get AI checking and build topic progress.</p><span class="arrow">Open topic checker â</span></button><button class="choice" data-page="syllabus"><span class="num">02</span><div class="icon">â</div><h2>Syllabus Questions</h2><p>Ask Cambridge IGCSE Physics questions by topic, with text, image and audio input.</p><span class="arrow">Open syllabus questions â</span></button><button class="choice" data-page="papers"><span class="num">03</span><div class="icon">â«</div><h2>Full Past Papers Checker</h2><p>Choose year, session and variant, upload the student paper, and let Physics AI-sistant retrieve the official mark scheme and check it.</p><span class="arrow">Open N.1 paper checker â</span></button></section></main>')}
function top(title,sub){return '<main class="wrap"><div class="pagehead"><div><div class="eyebrow">Physics AI-sistant</div><h1>'+title+'</h1><p class="hero p">'+sub+'</p></div><button class="back" data-page="home">â Dashboard</button></div>'}
function topicPage(){shell(top('Full Classified Topic Checker','Pick a syllabus route, then work topic by topic.')+'<div class="panel"><div class="filters"><div class="field"><label>Exam board</label><select><option>Cambridge IGCSE Physics</option><option>Edexcel International GCSE Physics</option></select></div><div class="field"><label>Specification</label><select><option>Current specification</option><option>My saved specification</option></select></div><div class="field"><label>Mode</label><select><option>Practice + AI checking</option><option>Review progress</option></select></div></div><div class="topic-grid">'+topics.map((t,i)=>'<button class="topic '+(i===state.topic?'active':'')+'" data-topic="'+i+'"><strong>'+t[0]+'</strong><small>'+t[1]+'</small></button>').join('')+'</div></div><div class="workspace" style="margin-top:18px"><aside class="panel side"><h3>Selected topic</h3><p><strong>'+topics[state.topic][0]+'</strong></p><p class="muted">'+topics[state.topic][1]+'</p><div class="notice">Progress<br><strong>0%</strong> Â· ready to start</div></aside><section class="panel"><div class="eyebrow">Question 1</div><div class="question">A car increases its velocity from 8 m/s to 20 m/s in 4 seconds. Calculate its acceleration.</div><div class="field" style="margin-top:18px"><label>Your answer</label><textarea id="topicAnswer" class="answer" placeholder="Show your working and include units..."></textarea></div><div class="actions"><button class="primary" id="checkTopic">Check with AI</button><button class="secondary" id="clearAnswer">Clear</button></div><div id="topicResult" class="result">'+(state.result||'')+'</div></section></div></main>')}
function syllabusPage(){shell(top('Physics AI-sistant','Cambridge IGCSE Physics tutor — choose a topic and ask using text, an image or your voice.')+'<div class="panel"><div class="filters"><div class="field"><label>Topic</label><select id="syTopic">'+topics.map(t=>'<option>'+t[0]+'</option>').join('')+'</select></div></div><div class="field" style="margin-top:18px"><label>Your Physics question</label><textarea id="syQuestion" class="answer" placeholder="Ask a Physics question..."></textarea></div><div class="input-tools"><div class="input-tool"><strong>Image</strong><label class="upload-button secondary" for="syImage">📷 Add image</label><input id="syImage" type="file" accept="image/*" hidden><span id="syImageStatus" class="file-status">No image selected.</span></div><div class="input-tool"><strong>Audio</strong><div class="audio-actions"><button type="button" class="secondary" id="startAudio">🎙️ Record question</button><button type="button" class="secondary hidden" id="stopAudio">⏹ Stop</button></div><span id="audioStatus" class="file-status">No audio recorded.</span></div></div><div class="actions"><button class="primary" id="askSyllabus">Ask Physics AI-sistant</button></div><div class="notice">Cambridge IGCSE Physics is fixed here. Teacher topic materials are used as additional context when available.</div><div id="syResult" class="result"></div></div></main>')}
function papersPage(){shell(top('03 · Full Past Papers Checker','Choose Paper 4 or Paper 6, then the exact year, session and variant. Upload the completed question paper and Physics AI-sistant will retrieve the matching official mark scheme.')+'<div class="panel"><div class="notice"><strong>How it works</strong><br>1. Choose Paper 4 or Paper 6.<br>2. Choose the year, session and variant.<br>3. Upload the completed question paper PDF.<br>4. Physics AI-sistant finds the exact official Cambridge mark scheme and checks the paper against it.</div><div class="filters" style="margin-top:18px"><div class="field"><label>Exam board</label><select id="paperBoard"><option>Cambridge IGCSE Physics</option></select></div><div class="field"><label>Paper</label><select id="paperType"><option value="4">Paper 4 — Theory</option><option value="6">Paper 6 — Alternative to Practical</option></select></div><div class="field"><label>Year</label><select id="paperYear"><option>Choose year</option><option>2026</option><option>2025</option><option>2024</option><option>2023</option><option>2022</option><option>2021</option><option>2020</option></select></div><div class="field"><label>Session</label><select id="paperSession"><option>Choose session</option><option>March</option><option>May/June</option><option>Oct/Nov</option></select></div><div class="field"><label>Variant</label><select id="paperVariant"><option value="41">Variant 1</option></select></div></div><section class="panel upload-card" style="margin-top:18px"><div class="eyebrow">Student paper</div><h2>Upload completed question paper PDF</h2><p class="muted">PDF only. Maximum 20 MB.</p><input id="studentPastPaperPdf" type="file" accept="application/pdf"/><div id="studentPastPaperStatus" class="file-status">No question paper selected.</div></section><div class="actions" style="margin-top:18px"><button class="primary" id="checkPastPaper">Find MS &amp; Check Paper</button><button class="secondary" id="clearPastPaper">Clear</button></div><div id="paperProgress" class="notice hidden" style="margin-top:16px"></div><div id="paperResult" class="result"></div></div></main>')}

async function uploadPdf(bucket,file,userId,label){return uploadAsset(bucket,file,userId,label,file.type||'application/pdf')}
async function uploadAsset(bucket,file,userId,label,contentType){const clean=(file.name||label).split(' ').join('-');const path=userId+'/ai-inputs/'+Date.now()+'-'+label+'-'+clean;const {error}=await sb.storage.from(bucket).upload(path,file,{contentType:contentType||file.type||'application/octet-stream',upsert:false});if(error)throw new Error(label+' upload failed: '+error.message);const {data,error:signError}=await sb.storage.from(bucket).createSignedUrl(path,3600);if(signError||!data?.signedUrl)throw new Error(label+' link creation failed: '+(signError?.message||'unknown error'));return data.signedUrl}
async function aiModal(question,{imageUrl=null,audioUrl=null}={}){question=await withKB(question);const {data,error}=await sb.functions.invoke('ai-route',{body:{mode:'tutor',modality:imageUrl?'image':audioUrl?'audio':'text',question,imageUrl,audioUrl}});if(error)throw new Error(error.message||'AI service unavailable');if(data?.error)throw new Error(data.error);return data}
function bind(){
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});
document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{state.topic=+b.dataset.topic;state.result=null;render()});
const ca=document.querySelector('#clearAnswer');if(ca)ca.onclick=()=>{state.answer='';state.result=null;render()};
const ct=document.querySelector('#checkTopic');if(ct)ct.onclick=async()=>{const a=document.querySelector('#topicAnswer').value.trim();if(!a)return;ct.disabled=true;ct.textContent='Checkingâ¦';try{const r=await ai('IGCSE Physics topic: '+topics[state.topic][0]+'\nQuestion: A car increases its velocity from 8 m/s to 20 m/s in 4 seconds. Calculate its acceleration.\nStudent answer: '+a+'\nCheck the working, units and final answer. Give concise student-friendly feedback.');state.result='<div class="ai-result-head"><span class="ai-avatar">IQ</span><div><strong>Physics AI-sistant AI</strong><small>Marking feedback</small></div></div><div class="ai-answer">'+renderAI(r.answer||r.result||JSON.stringify(r))+'</div>';state.answer=a}catch(e){state.result='<strong>Could not check yet</strong><p>'+escape(e.message)+'</p>'}render()};
const as=document.querySelector('#askSyllabus');const imageInput=document.querySelector('#syImage');const imageStatus=document.querySelector('#syImageStatus');const startAudio=document.querySelector('#startAudio');const stopAudio=document.querySelector('#stopAudio');const audioStatus=document.querySelector('#audioStatus');let recordedAudio=null;let recorder=null;let audioChunks=[];if(imageInput)imageInput.onchange=()=>{const f=imageInput.files[0];imageStatus.textContent=f?'✓ '+f.name:'No image selected.'};if(startAudio)startAudio.onclick=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});audioChunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)audioChunks.push(e.data)};recorder.onstop=()=>{recordedAudio=new Blob(audioChunks,{type:recorder.mimeType||'audio/webm'});audioStatus.textContent='✓ Voice question recorded ('+Math.round(recordedAudio.size/1024)+' KB)';stream.getTracks().forEach(t=>t.stop())};recorder.start();startAudio.classList.add('hidden');stopAudio.classList.remove('hidden');audioStatus.textContent='Recording…';}catch(e){audioStatus.textContent='Microphone unavailable: '+e.message}};if(stopAudio)stopAudio.onclick=()=>{if(recorder&&recorder.state!=='inactive')recorder.stop();stopAudio.classList.add('hidden');startAudio.classList.remove('hidden')};if(as)as.onclick=async()=>{const q=document.querySelector('#syQuestion').value.trim();const image=imageInput?.files?.[0]||null;if(!q&&!image&&!recordedAudio)return;as.disabled=true;as.textContent='Thinking…';const out=document.querySelector('#syResult');try{const{data:{user}}=await sb.auth.getUser();if(!user)throw new Error('Student session could not be created.');const imageUrl=image?await uploadAsset('answer-uploads',image,user.id,'question-image',image.type):null;const audioFile=recordedAudio?new File([recordedAudio],'question-audio.webm',{type:recordedAudio.type||'audio/webm'}):null;const audioUrl=audioFile?await uploadAsset('answer-uploads',audioFile,user.id,'question-audio',audioFile.type):null;const prompt='Answer as a Cambridge IGCSE Physics tutor. Topic: '+document.querySelector('#syTopic').value+'. Stay within the IGCSE Physics syllabus. Student question: '+(q||'[See attached image/audio question].');const r=await aiModal(prompt,{imageUrl,audioUrl});out.innerHTML='<div class="ai-result-head"><span class="ai-avatar">AI</span><div><strong>Physics AI-sistant</strong><small>Cambridge IGCSE Physics tutor</small></div></div><div class="ai-answer">'+renderAI(r.answer||r.result||JSON.stringify(r))+'</div>'}catch(e){out.innerHTML='<strong>Could not answer yet</strong><p>'+escape(e.message)+'</p>'}as.disabled=false;as.textContent='Ask Physics AI-sistant'};
}
function bindPaperControls(){const paperType=document.querySelector('#paperType');const paperVariant=document.querySelector('#paperVariant');const setVariants=()=>{if(!paperVariant)return;const p=paperType?.value||'4';const variants=p==='6'?['61','62','63']:['41','42','43'];paperVariant.innerHTML=variants.map(v=>'<option value="'+v+'">Variant '+v.slice(1)+'</option>').join('');paperVariant.value=variants[0]};if(paperType)paperType.onchange=setVariants;setVariants();const sf=document.querySelector('#studentPastPaperPdf');if(!sf)return;sf.onchange=()=>fileStatus('studentPastPaperStatus',sf.files[0]);const clear=document.querySelector('#clearPastPaper');if(clear)clear.onclick=()=>{sf.value='';fileStatus('studentPastPaperStatus');document.querySelector('#paperResult').innerHTML='';document.querySelector('#paperProgress').classList.add('hidden')};const check=document.querySelector('#checkPastPaper');if(check)check.onclick=()=>checkAutoPastPaper(sf.files[0])}
async function checkAutoPastPaper(studentFile){const result=document.querySelector('#paperResult');const progress=document.querySelector('#paperProgress');const button=document.querySelector('#checkPastPaper');if(!studentFile){result.innerHTML='<strong>Please upload the completed question paper.</strong>';return}if(studentFile.type!=='application/pdf'){result.innerHTML='<strong>PDF files only.</strong>';return}if(studentFile.size>20*1024*1024){result.innerHTML='<strong>PDF too large.</strong><p>The question paper must be 20 MB or smaller.</p>';return}const year=document.querySelector('#paperYear')?.value||'';const session=document.querySelector('#paperSession')?.value||'';const variant=document.querySelector('#paperVariant')?.value||'';const board=document.querySelector('#paperBoard')?.value||'';if(!year||year==='Choose year'||!session||session==='Choose session'||!/^([46][1-3])$/.test(variant)){result.innerHTML='<strong>Choose the year, session and variant first.</strong>';return}await ensureGuest();button.disabled=true;button.textContent='Preparingâ¦';progress.classList.remove('hidden');try{const {data:{user}}=await sb.auth.getUser();if(!user)throw new Error('Student session could not be created.');progress.textContent='Uploading the question paperâ¦';const studentUrl=await uploadPdf('answer-uploads',studentFile,user.id,'past-paper');progress.textContent='Finding the exact official mark scheme in the databaseâ¦';const r=await markPaper({mode:'mark',modality:'text',answerPdfUrl:studentUrl,answerPdfMimeType:'application/pdf',markSchemeLookup:{examBoard:board,year,session,variant},context:[board,year,session,'Paper '+(document.querySelector('#paperType')?.value||'4'),'Variant '+variant].join(' Â· ')});renderMarkResult(r);progress.classList.add('hidden')}catch(e){progress.classList.add('hidden');result.innerHTML='<strong>Could not check the paper.</strong><p>'+escape(e.message)+'</p>'}button.disabled=false;button.textContent='Find MS & Check Paper'}
async function withKB(q){try{const{data}=await sb.from('materials').select('title,content_text').not('content_text','is',null).limit(60);const words=new Set(String(q).toLowerCase().match(/[a-z]{4,}/g)||[]),ch=[];(data||[]).forEach(r=>r.content_text.split(/\n+/).flatMap(p=>p.match(/.{1,700}(\s|$)/g)||[]).forEach(p=>{const s=(p.toLowerCase().match(/[a-z]{4,}/g)||[]).filter(x=>words.has(x)).length;if(s>0)ch.push({t:r.title,p:p.trim(),s})}));ch.sort((a,b)=>b.s-a.s);let n=0;const use=ch.filter(c=>(n+=c.p.length)<6000);if(!use.length)return q;return 'Use the teacher knowledge base below when it covers the question, and name the material you used. If it does not cover it, answer from the official syllabus.\n\nKNOWLEDGE BASE:\n'+use.map(c=>'['+c.t+'] '+c.p).join('\n')+'\n\nSTUDENT QUESTION:\n'+q}catch{return q}}
async function ai(question){question=await withKB(question);const {data,error}=await sb.functions.invoke('ai-route',{body:{mode:'text',question}});if(error)throw new Error(error.message||'AI service unavailable');if(data?.error)throw new Error(data.error);return data}
function renderMarkResult(r){const result=document.querySelector('#paperResult');const x=r?.result;if(!x){result.innerHTML=aiCard('Marking feedback',r?.raw||'The AI did not return structured marking data.');return}const pct=typeof x.percentage==='number'?x.percentage:((x.marks_total?x.marks_awarded/x.marks_total:0)*100);const feedback=Array.isArray(x.feedback)?x.feedback.map(f=>'<div class="mark-comment"><div><strong>'+escape(f.point||'Mark-scheme point')+'</strong><span class="tag">'+(f.awarded?'Awarded':'Not awarded')+'</span></div><p>'+escape(f.explanation||'')+'</p></div>').join(''):'';result.innerHTML='<div class="ai-result-head"><span class="ai-avatar">IQ</span><div><strong>Physics AI-sistant AI</strong><small>Official mark-scheme check</small></div></div><div class="mark-summary"><div><span>Marks</span><strong>'+x.marks_awarded+' / '+x.marks_total+'</strong></div><div><span>Percentage</span><strong>'+Number(pct).toFixed(1)+'%</strong></div><div><span>Grade</span><strong>'+escape(x.grade||'â')+'</strong></div></div><div class="ai-answer"><h3>Comments</h3>'+feedback+'</div>'}
function renderAI(value){
  const source=String(value??'').trim();
  if(!source)return '';
  const math=[];
  function stash(tex,display){
    const id='@@MATH_'+math.length+'@@';
    math.push({tex:tex.trim(),display:display});
    return id;
  }
  function extract(text,open,close,display){
    let out='',i=0;
    while(i<text.length){
      const s=text.indexOf(open,i);
      if(s<0){out+=text.slice(i);break;}
      out+=text.slice(i,s);
      const e=text.indexOf(close,s+open.length);
      if(e<0){out+=text.slice(s);break;}
      out+=stash(text.slice(s+open.length,e),display);
      i=e+close.length;
    }
    return out;
  }
  let text=source;
  text=extract(text,'\\[','\\]',true);
  text=extract(text,'$$','$$',true);
  text=extract(text,'\\(','\\)',false);
  text=extract(text,'$','$',false);
  let html=marked.parse(text,{breaks:true});
  html=html.replace(/@@MATH_(\d+)@@/g,function(_,n){
    const m=math[Number(n)];
    try{return katex.renderToString(m.tex,{displayMode:m.display,throwOnError:false})}
    catch(e){return '<code>'+escape(m.tex)+'</code>'}
  });
  return DOMPurify.sanitize(html,{USE_PROFILES:{html:true}});
}

function render(){if(state.page==='home')home();if(state.page==='topic')topicPage();if(state.page==='syllabus')syllabusPage();if(state.page==='papers')papersPage()}
ensureGuest().finally(render);