import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_KEY, GUEST } from './config.js';

const sb = createClient(SUPABASE_URL, SUPABASE_KEY);
const app = document.querySelector('#app');
const topics = [
  ['Forces and motion','Motion, forces, momentum and pressure'],
  ['Energy','Energy stores, transfers, work, power and efficiency'],
  ['Thermal physics','Particle model, temperature, heating and cooling'],
  ['Waves','Wave properties, sound, light and electromagnetic waves'],
  ['Electricity','Circuits, current, voltage, resistance and electrical power'],
  ['Magnetism','Magnetic fields, motors, generators and transformers'],
  ['Radioactivity','Atomic structure, radiation, decay and safety'],
  ['Space physics','Earth, satellites, stars and the wider universe']
];
let state={page:'home',topic:0,result:null};

function header(){return '<header class="topbar"><button class="brand" style="border:0;background:none;padding:0" data-page="home">Physics<span>IQ</span></button><div class="header-right"><div class="model-chip"><span class="model-dot"></span><span>PhysicsIQ AI</span><small>IGCSE Physics</small></div><div class="status"><i class="dot"></i> Workspace</div></div></header>'}
function shell(content){app.innerHTML='<div class="shell">'+header()+content+'</div>';bind()}
function home(){shell('<main class="wrap"><section class="hero"><div class="eyebrow">IGCSE Physics workspace</div><h1>Choose what you want to do.</h1><p>No clutter. Pick a Physics task and go straight into the work.</p></section><section class="choices"><button class="choice" data-page="topic"><span class="num">01</span><div class="icon">⌁</div><h2>Full Classified Topic Checker</h2><p>Choose a topic and subtopic, practise questions, get AI checking and build topic progress.</p><span class="arrow">Open topic checker →</span></button><button class="choice" data-page="syllabus"><span class="num">02</span><div class="icon">⌘</div><h2>Syllabus Questions</h2><p>Ask questions by board, specification and topic, with syllabus-focused answers.</p><span class="arrow">Open syllabus questions →</span></button><button class="choice" data-page="papers"><span class="num">03</span><div class="icon">◫</div><h2>Full Past Papers Checker</h2><p>Upload a student paper and its official mark scheme, then let PhysicsIQ mark the work and comment.</p><span class="arrow">Open N.1 paper checker →</span></button></section><div class="footer-note">Login and teacher tools can be added later without changing these three workspaces.</div></main>')}
function top(title,sub){return '<main class="wrap"><div class="pagehead"><div><div class="eyebrow">PhysicsIQ</div><h1>'+title+'</h1><p class="hero p">'+sub+'</p></div><button class="back" data-page="home">← Dashboard</button></div>'}
function topicPage(){shell(top('Full Classified Topic Checker','Pick a syllabus route, then work topic by topic.')+'<div class="panel"><div class="filters"><div class="field"><label>Exam board</label><select><option>Cambridge IGCSE Physics</option><option>Edexcel International GCSE Physics</option></select></div><div class="field"><label>Specification</label><select><option>Current specification</option><option>My saved specification</option></select></div><div class="field"><label>Mode</label><select><option>Practice + AI checking</option><option>Review progress</option></select></div></div><div class="topic-grid">'+topics.map((t,i)=>'<button class="topic '+(i===state.topic?'active':'')+'" data-topic="'+i+'"><strong>'+t[0]+'</strong><small>'+t[1]+'</small></button>').join('')+'</div></div><div class="workspace" style="margin-top:18px"><aside class="panel side"><h3>Selected topic</h3><p><strong>'+topics[state.topic][0]+'</strong></p><p class="muted">'+topics[state.topic][1]+'</p><div class="notice">Progress<br><strong>0%</strong> · ready to start</div></aside><section class="panel"><div class="eyebrow">Question 1</div><div class="question">A car increases its velocity from 8 m/s to 20 m/s in 4 seconds. Calculate its acceleration.</div><div class="field" style="margin-top:18px"><label>Your answer</label><textarea id="topicAnswer" class="answer" placeholder="Show your working and include units..."></textarea></div><div class="actions"><button class="primary" id="checkTopic">Check with AI</button><button class="secondary" id="clearAnswer">Clear</button></div><div id="topicResult" class="result">'+(state.result||'')+'</div></section></div></main>')}
function syllabusPage(){shell(top('Syllabus Questions','Choose the academic boundary first, then ask your question.')+'<div class="panel"><div class="filters"><div class="field"><label>Board</label><select id="board"><option>Cambridge</option><option>Edexcel</option></select></div><div class="field"><label>Specification</label><select id="spec"><option>IGCSE Physics</option></select></div><div class="field"><label>Topic</label><select id="syTopic">'+topics.map(t=>'<option>'+t[0]+'</option>').join('')+'</select></div></div><div class="field" style="margin-top:18px"><label>Your syllabus question</label><textarea id="syQuestion" class="answer" placeholder="Ask a Physics question..."></textarea></div><div class="actions"><button class="primary" id="askSyllabus">Ask PhysicsIQ</button></div><div class="notice">The syllabus is the boundary. Teacher resources can be connected later and used as additional context without replacing the specification.</div><div id="syResult" class="result"></div></div></main>')}
function papersPage(){shell(top('N.1 · Student Paper Checker','Upload the student PDF first, then upload the official mark scheme PDF. PhysicsIQ will check the student work against the supplied scheme and return comments.')+'<div class="panel"><div class="notice"><strong>How it works</strong><br>1. Upload the student’s completed paper as a PDF.<br>2. Upload the official mark scheme as a PDF.<br>3. Press <strong>Check paper with AI</strong>.<br>4. PhysicsIQ reviews the pages and returns marks, percentage and comments based on the supplied mark scheme.</div><div class="filters" style="margin-top:18px"><div class="field"><label>Exam board</label><select id="paperBoard"><option>Cambridge IGCSE Physics</option><option>Edexcel International GCSE Physics</option></select></div><div class="field"><label>Session</label><select id="paperSession"><option>Choose session</option><option>May/June</option><option>Oct/Nov</option><option>March</option></select></div><div class="field"><label>Paper</label><select id="paperNumber"><option>Choose paper</option><option>Paper 1</option><option>Paper 2</option><option>Paper 4</option></select></div></div><div class="workspace" style="margin-top:18px"><section class="panel upload-card"><div class="eyebrow">01 · Student work</div><h2>Upload student paper PDF</h2><p class="muted">PDF only. The paper should contain the student’s completed answers and workings.</p><input id="studentPdf" type="file" accept="application/pdf"/><div id="studentPdfStatus" class="file-status">No student PDF selected.</div></section><section class="panel upload-card"><div class="eyebrow">02 · Official marking</div><h2>Upload mark scheme PDF</h2><p class="muted">Use the official mark scheme for this exact paper.</p><input id="markSchemePdf" type="file" accept="application/pdf"/><div id="markSchemeStatus" class="file-status">No mark scheme selected.</div></section></div><div class="actions" style="margin-top:18px"><button class="primary" id="checkPaper">Check paper with AI</button><button class="secondary" id="clearPaper">Clear files</button></div><div id="paperProgress" class="notice hidden" style="margin-top:16px"></div><div id="paperResult" class="result"></div></div></main>')}
async function ensureGuest(){if(!GUEST)return;const {data}=await sb.auth.getSession();if(!data.session){const {error}=await sb.auth.signInAnonymously();if(error)console.warn(error.message)}}
async function ai(question){const {data,error}=await sb.functions.invoke('ai-route',{body:{mode:'text',question}});if(error)throw new Error(error.message||'AI service unavailable');if(data?.error)throw new Error(data.error);return data}
async function markPaper(payload){const {data,error}=await sb.functions.invoke('ai-route',{body:payload});if(error)throw new Error(error.message||'AI service unavailable');if(data?.error)throw new Error(data.detail||data.error);return data}
function escape(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'","&#39;").replaceAll('\n','<br>')}
function renderAI(value){const source=String(value??'').trim();if(!source)return '';let html=source;const math=[];function stash(tex,display){const id='@@MATH_'+math.length+'@@';math.push({tex:tex.trim(),display});return id}function extract(text,open,close,display){let out='',i=0;while(i<text.length){const s=text.indexOf(open,i);if(s<0){out+=text.slice(i);break}out+=text.slice(i,s);const e=text.indexOf(close,s+open.length);if(e<0){out+=text.slice(s);break}out+=stash(text.slice(s+open.length,e),display);i=e+close.length}return out}html=extract(html,'\\[','\\]',true);html=extract(html,'$$','$$',true);html=extract(html,'\\(','\\)',false);html=extract(html,'$','$',false);if(window.marked)html=marked.parse(html,{breaks:true});else html=escape(source);math.forEach((m,index)=>{const token='@@MATH_'+index+'@@';let rendered;try{rendered=window.katex.renderToString(m.tex,{displayMode:m.display,throwOnError:false})}catch(e){rendered='<code>'+escape(m.tex)+'</code>'}html=html.split(token).join(rendered)});return window.DOMPurify?DOMPurify.sanitize(html,{USE_PROFILES:{html:true}}):html}
function aiCard(label,body){return '<div class="ai-result-head"><span class="ai-avatar">IQ</span><div><strong>PhysicsIQ AI</strong><small>'+label+'</small></div></div><div class="ai-answer">'+renderAI(body)+'</div>'}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;state.result=null;render()});document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{state.topic=Number(b.dataset.topic);render()});const clear=document.querySelector('#clearAnswer');if(clear)clear.onclick=()=>{document.querySelector('#topicAnswer').value='';document.querySelector('#topicResult').innerHTML=''};const ct=document.querySelector('#checkTopic');if(ct)ct.onclick=async()=>{const a=document.querySelector('#topicAnswer').value.trim();if(!a)return;ct.disabled=true;ct.textContent='Checking…';try{const r=await ai('IGCSE Physics topic: '+topics[state.topic][0]+'\nQuestion: A car increases its velocity from 8 m/s to 20 m/s in 4 seconds. Calculate its acceleration.\nStudent answer: '+a+'\nCheck the working, units and final answer. Give concise student-friendly feedback.');document.querySelector('#topicResult').innerHTML=aiCard('Marking feedback',r.answer||r.result||JSON.stringify(r));}catch(e){document.querySelector('#topicResult').innerHTML='<strong>Could not check yet</strong><p>'+escape(e.message)+'</p>'}ct.disabled=false;ct.textContent='Check with AI'};const as=document.querySelector('#askSyllabus');if(as)as.onclick=async()=>{const q=document.querySelector('#syQuestion').value.trim();if(!q)return;as.disabled=true;as.textContent='Thinking…';const out=document.querySelector('#syResult');try{const r=await ai('Answer as an IGCSE Physics tutor. Board: '+document.querySelector('#board').value+'. Specification: '+document.querySelector('#spec').value+'. Topic: '+document.querySelector('#syTopic').value+'. The academic boundary is the syllabus. Question: '+q);out.innerHTML=aiCard('IGCSE Physics tutor',r.answer||r.result||JSON.stringify(r));}catch(e){out.innerHTML='<strong>Could not answer yet</strong><p>'+escape(e.message)+'</p>'}as.disabled=false;as.textContent='Ask PhysicsIQ'};bindPaperControls()}
function fileStatus(id,file){const el=document.querySelector('#'+id);if(!el)return;el.textContent=file?file.name+' · '+Math.round(file.size/1024)+' KB':'No file selected.';el.className='file-status '+(file?'ready':'')}
function bindPaperControls(){const sf=document.querySelector('#studentPdf');const mf=document.querySelector('#markSchemePdf');if(!sf||!mf)return;sf.onchange=()=>fileStatus('studentPdfStatus',sf.files[0]);mf.onchange=()=>fileStatus('markSchemeStatus',mf.files[0]);const clear=document.querySelector('#clearPaper');if(clear)clear.onclick=()=>{sf.value='';mf.value='';fileStatus('studentPdfStatus');fileStatus('markSchemeStatus');document.querySelector('#paperResult').innerHTML='';document.querySelector('#paperProgress').classList.add('hidden')};const check=document.querySelector('#checkPaper');if(check)check.onclick=()=>checkUploadedPaper(sf.files[0],mf.files[0])}
async function uploadPdf(bucket,file,userId,label){const clean=file.name.split(' ').join('-');const path=userId+'/n1/'+Date.now()+'-'+label+'-'+clean;const {error}=await sb.storage.from(bucket).upload(path,file,{contentType:'application/pdf',upsert:false});if(error)throw new Error(label+' upload failed: '+error.message);const {data,error:signError}=await sb.storage.from(bucket).createSignedUrl(path,3600);if(signError||!data?.signedUrl)throw new Error(label+' link creation failed: '+(signError?.message||'unknown error'));return data.signedUrl}
async function checkUploadedPaper(studentFile,markFile){const result=document.querySelector('#paperResult');const progress=document.querySelector('#paperProgress');const button=document.querySelector('#checkPaper');if(!studentFile||!markFile){result.innerHTML='<strong>Please upload both PDFs.</strong><p>Select the student paper and the official mark scheme before checking.</p>';return}if(studentFile.type!=='application/pdf'||markFile.type!=='application/pdf'){result.innerHTML='<strong>PDF files only.</strong>';return}if(studentFile.size>6*1024*1024||markFile.size>6*1024*1024){result.innerHTML='<strong>PDF too large for this upload mode.</strong><p>Please use PDFs under 6 MB each.</p>';return}await ensureGuest();button.disabled=true;button.textContent='Preparing…';progress.classList.remove('hidden');progress.textContent='Uploading the student paper…';try{const {data:{user}}=await sb.auth.getUser();if(!user)throw new Error('Student session could not be created.');const studentUrl=await uploadPdf('answer-uploads',studentFile,user.id,'student');progress.textContent='Uploading the official mark scheme…';const markUrl=await uploadPdf('mark-schemes',markFile,user.id,'scheme');progress.textContent='PhysicsIQ is checking every supplied page against the mark scheme…';const context=[document.querySelector('#paperBoard')?.value||'',document.querySelector('#paperSession')?.value||'',document.querySelector('#paperNumber')?.value||''].filter(Boolean).join(' · ');const r=await markPaper({mode:'mark',modality:'text',answerPdfUrl:studentUrl,answerPdfMimeType:'application/pdf',markSchemeUrl:markUrl,markSchemeMimeType:'application/pdf',context});renderMarkResult(r);progress.classList.add('hidden')}catch(e){progress.classList.add('hidden');result.innerHTML='<strong>Could not check the paper.</strong><p>'+escape(e.message)+'</p>'}button.disabled=false;button.textContent='Check paper with AI'}
function renderMarkResult(r){const result=document.querySelector('#paperResult');const x=r?.result;if(!x){result.innerHTML=aiCard('Marking feedback',r?.raw||'The AI did not return structured marking data.');return}const pct=typeof x.percentage==='number'?x.percentage:((x.marks_total?x.marks_awarded/x.marks_total:0)*100);const feedback=Array.isArray(x.feedback)?x.feedback.map(f=>'<div class="mark-comment"><div><strong>'+escape(f.point||'Mark-scheme point')+'</strong><span class="tag">'+(f.awarded?'Awarded':'Not awarded')+'</span></div><p>'+escape(f.explanation||'')+'</p></div>').join(''):'';result.innerHTML='<div class="ai-result-head"><span class="ai-avatar">IQ</span><div><strong>PhysicsIQ AI</strong><small>Official mark-scheme check</small></div></div><div class="mark-summary"><div><span>Marks</span><strong>'+x.marks_awarded+' / '+x.marks_total+'</strong></div><div><span>Percentage</span><strong>'+Number(pct).toFixed(1)+'%</strong></div><div><span>Grade</span><strong>'+escape(x.grade||'—')+'</strong></div></div><div class="ai-answer"><h3>Comments</h3>'+feedback+'</div>'}
function render(){if(state.page==='home')home();if(state.page==='topic')topicPage();if(state.page==='syllabus')syllabusPage();if(state.page==='papers')papersPage()}
ensureGuest().finally(render);