import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_KEY, GUEST } from './config.js';

const sb = createClient(SUPABASE_URL, SUPABASE_KEY);
const app = document.querySelector('#app');
const topics = [
  ['Forces and motion','Motion, forces, momentum and pressure'],
  ['Energy','Energy stores, transfers, work, power and efficiency'],
  ['Thermal physics','Particle model, temperature, heating and cooling'],
  ['Waves','Wave properties, sound, light and electromagnetic waves'],
  ['Electricity','Circuits, current, voltage, resistance and electrical power'],
  ['Magnetism','Magnetic fields, motors, generators and transformers'],
  ['Radioactivity','Atomic structure, radiation, decay and safety'],
  ['Space physics','Earth, satellites, stars and the wider universe']
];
let state={page:'home',topic:0,result:null};

function header(){return '<header class="topbar"><button class="brand" style="border:0;background:none;padding:0" data-page="home">Physics<span>IQ</span></button><div class="header-right"><div class="model-chip"><span class="model-dot"></span><span>PhysicsIQ AI</span><small>IGCSE Physics</small></div><div class="status"><i class="dot"></i> Workspace</div></div></header>'}
function shell(content){app.innerHTML='<div class="shell">'+header()+content+'</div>';bind()}
function home(){shell('<main class="wrap"><section class="hero"><div class="eyebrow">IGCSE Physics workspace</div><h1>Choose what you want to do.</h1><p>No clutter. Pick a Physics task and go straight into the work.</p></section><section class="choices"><button class="choice" data-page="topic"><span class="num">01</span><div class="icon">⌁</div><h2>Full Classified Topic Checker</h2><p>Choose a topic and subtopic, practise questions, get AI checking and build topic progress.</p><span class="arrow">Open topic checker →</span></button><button class="choice" data-page="syllabus"><span class="num">02</span><div class="icon">⌘</div><h2>Syllabus Questions</h2><p>Ask questions by board, specification and topic, with syllabus-focused answers.</p><span class="arrow">Open syllabus questions →</span></button><button class="choice" data-page="papers"><span class="num">03</span><div class="icon">◫</div><h2>Full Past Papers Checker</h2><p>Choose year, session and variant, upload the student paper, and let PhysicsIQ retrieve the official mark scheme and check it.</p><span class="arrow">Open N.1 paper checker →</span></button></section><div class="footer-note">Login and teacher tools can be added later without changing these three workspaces.</div></main>')}
function top(title,sub){return '<main class="wrap"><div class="pagehead"><div><div class="eyebrow">PhysicsIQ</div><h1>'+title+'</h1><p class="hero p">'+sub+'</p></div><button class="back" data-page="home">← Dashboard</button></div>'}
function topicPage(){shell(top('Full Classified Topic Checker','Pick a syllabus route, then work topic by topic.')+'<div class="panel"><div class="filters"><div class="field"><label>Exam board</label><select><option>Cambridge IGCSE Physics</option><option>Edexcel International GCSE Physics</option></select></div><div class="field"><label>Specification</label><select><option>Current specification</option><option>My saved specification</option></select></div><div class="field"><label>Mode</label><select><option>Practice + AI checking</option><option>Review progress</option></select></div></div><div class="topic-grid">'+topics.map((t,i)=>'<button class="topic '+(i===state.topic?'active':'')+'" data-topic="'+i+'"><strong>'+t[0]+'</strong><small>'+t[1]+'</small></button>').join('')+'</div></div><div class="workspace" style="margin-top:18px"><aside class="panel side"><h3>Selected topic</h3><p><strong>'+topics[state.topic][0]+'</strong></p><p class="muted">'+topics[state.topic][1]+'</p><div class="notice">Progress<br><strong>0%</strong> · ready to start</div></aside><section class="panel"><div class="eyebrow">Question 1</div><div class="question">A car increases its velocity from 8 m/s to 20 m/s in 4 seconds. Calculate its acceleration.</div><div class="field" style="margin-top:18px"><label>Your answer</label><textarea id="topicAnswer" class="answer" placeholder="Show your working and include units..."></textarea></div><div class="actions"><button class="primary" id="checkTopic">Check with AI</button><button class="secondary" id="clearAnswer">Clear</button></div><div id="topicResult" class="result">'+(state.result||'')+'</div></section></div></main>')}
function syllabusPage(){shell(top('Syllabus Questions','Choose the academic boundary first, then ask your question.')+'<div class="panel"><div class="filters"><div class="field"><label>Board</label><select id="board"><option>Cambridge</option><option>Edexcel</option></select></div><div class="field"><label>Specification</label><select id="spec"><option>IGCSE Physics</option></select></div><div class="field"><label>Topic</label><select id="syTopic">'+topics.map(t=>'<option>'+t[0]+'</option>').join('')+'</select></div></div><div class="field" style="margin-top:18px"><label>Your syllabus question</label><textarea id="syQuestion" class="answer" placeholder="Ask a Physics question..."></textarea></div><div class="actions"><button class="primary" id="askSyllabus">Ask PhysicsIQ</button></div><div class="notice">The syllabus is the boundary. Teacher resources can be connected later and used as additional context without replacing the specification.</div><div id="syResult" class="result"></div></div></main>')}
function papersPage(){shell(top('03 · Full Past Papers Checker','Choose the exact year, session and variant. Upload the completed question paper and PhysicsIQ will retrieve the matching official mark scheme from the database automatically.')+'<div class="panel"><div class="notice"><strong>How it works</strong><br>1. Choose the exam board, year, session and variant.<br>2. Upload the student’s completed question paper PDF.<br>3. PhysicsIQ finds the exact official mark scheme stored in the database.<br>4. The AI checks the student paper against that mark scheme and saves the result.</div><div class="filters" style="margin-top:18px"><div class="field"><label>Exam board</label><select id="paperBoard"><option>Cambridge IGCSE Physics</option><option>Edexcel International GCSE Physics</option></select></div><div class="field"><label>Year</label><select id="paperYear"><option>Choose year</option><option>2026</option><option>2025</option><option>2024</option><option>2023</option><option>2022</option><option>2021</option><option>2020</option></select></div><div class="field"><label>Session</label><select id="paperSession"><option>Choose session</option><option>March</option><option>May/June</option><option>Oct/Nov</option></select></div><div class="field"><label>Variant</label><select id="paperVariant"><option>Choose variant</option><option>1</option><option>2</option><option>3</option></select></div></div><section class="panel upload-card" style="margin-top:18px"><div class="eyebrow">Student paper</div><h2>Upload completed question paper PDF</h2><p class="muted">PDF only. Maximum 20 MB.</p><input id="studentPastPaperPdf" type="file" accept="application/pdf"/><div id="studentPastPaperStatus" class="file-status">No question paper selected.</div></section><div class="actions" style="margin-top:18px"><button class="primary" id="checkPastPaper">Find MS &amp; Check Paper</button><button class="secondary" id="clearPastPaper">Clear</button></div><div id="paperProgress" class="notice hidden" style="margin-top:16px"></div><div id="paperResult" class="result"></div></div></main>')}
async function uploadPdf(bucket,file,userId,label){const clean=file.name.split(' ').join('-');const path=userId+'/n1/'+Date.now()+'-'+label+'-'+clean;const {error}=await sb.storage.from(bucket).upload(path,file,{contentType:'application/pdf',upsert:false});if(error)throw new Error(label+' upload failed: '+error.message);const {data,error:signError}=await sb.storage.from(bucket).createSignedUrl(path,3600);if(signError||!data?.signedUrl)throw new Error(label+' link creation failed: '+(signError?.message||'unknown error'));return data.signedUrl}
function bindPaperControls(){const sf=document.querySelector('#studentPastPaperPdf');if(!sf)return;sf.onchange=()=>fileStatus('studentPastPaperStatus',sf.files[0]);const clear=document.querySelector('#clearPastPaper');if(clear)clear.onclick=()=>{sf.value='';fileStatus('studentPastPaperStatus');document.querySelector('#paperResult').innerHTML='';document.querySelector('#paperProgress').classList.add('hidden')};const check=document.querySelector('#checkPastPaper');if(check)check.onclick=()=>checkAutoPastPaper(sf.files[0])}
async function checkAutoPastPaper(studentFile){const result=document.querySelector('#paperResult');const progress=document.querySelector('#paperProgress');const button=document.querySelector('#checkPastPaper');if(!studentFile){result.innerHTML='<strong>Please upload the completed question paper.</strong>';return}if(studentFile.type!=='application/pdf'){result.innerHTML='<strong>PDF files only.</strong>';return}if(studentFile.size>20*1024*1024){result.innerHTML='<strong>PDF too large.</strong><p>The question paper must be 20 MB or smaller.</p>';return}const year=document.querySelector('#paperYear')?.value||'';const session=document.querySelector('#paperSession')?.value||'';const variant=document.querySelector('#paperVariant')?.value||'';const board=document.querySelector('#paperBoard')?.value||'';if(!year||year==='Choose year'||!session||session==='Choose session'||!variant||variant==='Choose variant'){result.innerHTML='<strong>Choose the year, session and variant first.</strong>';return}await ensureGuest();button.disabled=true;button.textContent='Preparing…';progress.classList.remove('hidden');try{const {data:{user}}=await sb.auth.getUser();if(!user)throw new Error('Student session could not be created.');progress.textContent='Uploading the question paper…';const studentUrl=await uploadPdf('answer-uploads',studentFile,user.id,'past-paper');progress.textContent='Finding the exact official mark scheme in the database…';const r=await markPaper({mode:'mark',modality:'text',answerPdfUrl:studentUrl,answerPdfMimeType:'application/pdf',markSchemeLookup:{examBoard:board,year,session,variant},context:[board,year,session,'Variant '+variant].join(' · ')});renderMarkResult(r);progress.classList.add('hidden')}catch(e){progress.classList.add('hidden');result.innerHTML='<strong>Could not check the paper.</strong><p>'+escape(e.message)+'</p>'}button.disabled=false;button.textContent='Find MS & Check Paper'}
function renderMarkResult(r){const result=document.querySelector('#paperResult');const x=r?.result;if(!x){result.innerHTML=aiCard('Marking feedback',r?.raw||'The AI did not return structured marking data.');return}const pct=typeof x.percentage==='number'?x.percentage:((x.marks_total?x.marks_awarded/x.marks_total:0)*100);const feedback=Array.isArray(x.feedback)?x.feedback.map(f=>'<div class="mark-comment"><div><strong>'+escape(f.point||'Mark-scheme point')+'</strong><span class="tag">'+(f.awarded?'Awarded':'Not awarded')+'</span></div><p>'+escape(f.explanation||'')+'</p></div>').join(''):'';result.innerHTML='<div class="ai-result-head"><span class="ai-avatar">IQ</span><div><strong>PhysicsIQ AI</strong><small>Official mark-scheme check</small></div></div><div class="mark-summary"><div><span>Marks</span><strong>'+x.marks_awarded+' / '+x.marks_total+'</strong></div><div><span>Percentage</span><strong>'+Number(pct).toFixed(1)+'%</strong></div><div><span>Grade</span><strong>'+escape(x.grade||'—')+'</strong></div></div><div class="ai-answer"><h3>Comments</h3>'+feedback+'</div>'}
function render(){if(state.page==='home')home();if(state.page==='topic')topicPage();if(state.page==='syllabus')syllabusPage();if(state.page==='papers')papersPage()}
ensureGuest().finally(render);