import {sb,ai,nice,openAuth} from './app.js';
const $=s=>document.querySelector(s);
const esc=t=>String(t??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const TOPICS=['Motion','Forces and Newton laws','Work, energy and power','Pressure','Thermal physics','Waves, light and sound','Electricity','Magnetism and electromagnetism','Atomic and nuclear physics','Space physics'];
document.querySelectorAll('#topicSel,#synSel,#tUnit').forEach(s=>TOPICS.forEach(t=>s.add(new Option(t,t))));
const say=(el,t,ok)=>{el.textContent=t;el.className='msg '+(t?(ok?'ok':'bad'):'')};

const pick=(q,rows)=>{const w=new Set(q.toLowerCase().match(/[a-z]{4,}/g)||[]),ch=[];rows.forEach(r=>(r.content_text||'').split(/\n+/).forEach(p=>{if(p.trim().length>20)ch.push({t:r.title,p:p.slice(0,700),s:(p.toLowerCase().match(/[a-z]{4,}/g)||[]).filter(x=>w.has(x)).length})}));ch.sort((a,b)=>b.s-a.s);let n=0;return ch.filter(c=>(n+=c.p.length)<6000).map(c=>`[${c.t}] ${c.p}`).join('\n')};

$('#synGo').onclick=async()=>{const m=$('#synMsg'),q=$('#synQ').value.trim(),u=$('#synSel').value;if(!q)return;say(m,'Thinking...',true);$('#synOut').innerHTML='';$('#synGo').disabled=true;try{const{data}=await sb.from('materials').select('title,file_url,content_text').eq('unit_name',u).limit(20);const rows=data||[],ctx=pick(q,rows);const r=await ai({mode:'tutor',modality:'text',question:ctx?`Answer using the teacher materials below and say which material you used. If they do not cover the question, say so, then answer from general IGCSE knowledge.\n\nTEACHER MATERIALS:\n${ctx}\n\nSTUDENT QUESTION: ${q}`:q});say(m,'');const vids=rows.filter(x=>/^https?:\/\//.test(x.file_url||'')).map(x=>`<a href='${esc(x.file_url)}' target='_blank' rel='noopener'>▶ ${esc(x.title)}</a>`).join(' · ');$('#synOut').innerHTML=`<div class='b bot' style='max-width:100%;margin-top:24px'><small>Tutor</small><p>${esc(r.answer)}</p>${vids?`<p style='margin-top:10px'>Teacher videos: ${vids}</p>`:''}<code>${esc(r.modelUsed)} · ${rows.length?'used '+rows.length+' teacher material(s)':'no teacher materials for this topic yet'}</code></div>`}catch(x){say(m,nice(x.message))}$('#synGo').disabled=false};

let uid=null,anon=true,role=null;
sb.auth.onAuthStateChange(async(_e,s)=>{uid=s?.user?.id||null;anon=!!s?.user?.is_anonymous;role=null;if(uid&&!anon){const{data}=await sb.from('profiles').select('role').eq('id',uid).maybeSingle();role=data?.role}gate()});
function gate(){const g=$('#tGate');$('#tPanel').hidden=role!=='teacher';g.hidden=role==='teacher';if(role==='teacher'){list();return}
g.innerHTML=(!uid||anon)?`<p>Teachers sign in here to upload materials.</p><button class='btn' id='tSign'>Sign in or create a teacher account</button>`:`<p>You are signed in. Enter the teacher code to unlock uploads.</p><label>Teacher code<input id='tCode'></label><button class='btn' id='tClaim'>Unlock</button><p id='tCm' class='msg'></p>`;
if($('#tSign'))$('#tSign').onclick=()=>openAuth(true);
if($('#tClaim'))$('#tClaim').onclick=async()=>{const{data}=await sb.rpc('claim_teacher',{code:$('#tCode').value.trim()});if(data){role='teacher';gate()}else say($('#tCm'),'That code is not right.')}}

async function text(f){const n=f.name.toLowerCase();if(/\.(txt|md)$/.test(n))return f.text();const{default:JSZip}=await import('https://cdn.jsdelivr.net/npm/jszip@3.10.1/+esm');const z=await JSZip.loadAsync(f);const num=k=>parseInt(k.match(/\d+/g).pop());const names=n.endsWith('.pptx')?Object.keys(z.files).filter(k=>/^ppt\/slides\/slide\d+\.xml$/.test(k)).sort((a,b)=>num(a)-num(b)):['word/document.xml'];let out='';for(const k of names){const x=await z.file(k).async('string');out+=x.replace(/<\/a:p>|<\/w:p>/g,'\n').replace(/<[^>]+>/g,'').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>')+'\n'}return out}

$('#tFile').onchange=e=>{$('#tLbl').textContent=e.target.files[0]?'✓ '+e.target.files[0].name:'＋ PowerPoint, Word or text notes'};
$('#tGo').onclick=async()=>{const m=$('#tMsg'),f=$('#tFile').files[0],yt=$('#tYt').value.trim(),t=$('#tTxt').value.trim(),title=$('#tTitle').value.trim();if(!title||(!f&&!yt&&!t))return say(m,'Add a title and at least a file, a link or some notes.');if(yt&&!/^https?:\/\//.test(yt))return say(m,'The video link must start with https://');$('#tGo').disabled=true;say(m,'Uploading...',true);try{const body=((f?await text(f):'')+'\n'+t).trim();const{error}=await sb.from('materials').insert({teacher_id:uid,title,type:'unit',unit_name:$('#tUnit').value,file_name:f?.name||null,file_size:f?.size||null,file_url:yt||null,description:yt?'video':'notes',content_text:body.slice(0,60000)||null});if(error)throw error;say(m,'Uploaded. Students can now get answers from this.',true);['#tTitle','#tYt','#tTxt'].forEach(s=>$(s).value='');$('#tFile').value='';$('#tLbl').textContent='＋ PowerPoint, Word or text notes';list()}catch(x){say(m,x.message)}$('#tGo').disabled=false};

async function list(){const{data}=await sb.from('materials').select('id,title,unit_name,file_url').eq('teacher_id',uid).order('created_at',{ascending:false});$('#tList').innerHTML=(data||[]).map(r=>`<div class='card'><p><b>${esc(r.title)}</b> · ${esc(r.unit_name)}${r.file_url?' · ▶ video':''}</p><button class='link' data-id='${r.id}'>Delete</button></div>`).join('')||`<p class='empty'>Nothing uploaded yet.</p>`;$('#tList').querySelectorAll('button').forEach(b=>b.onclick=async()=>{await sb.from('materials').delete().eq('id',b.dataset.id);list()})}
