import { createClient } from "jsr:@supabase/supabase-js@2";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SECRET_KEY=(()=>{const legacy=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")?.trim();if(legacy)return legacy;try{return JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}").default?.trim()||null}catch{return null}})();
const PUBLISHABLE_KEY=(()=>{const legacy=Deno.env.get("SUPABASE_ANON_KEY")?.trim();if(legacy)return legacy;try{return JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")||"{}").default?.trim()||null}catch{return null}})();
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json",...cors}});
const emailForUsername=(username:string)=>`${username.toLowerCase()}@users.physics-ai-sistant.local`;
const cleanUsername=(v:unknown)=>String(v||"").trim().toLowerCase();
async function teacherFromRequest(req:Request){if(!SECRET_KEY)throw new Error("supabase_secret_missing");const auth=req.headers.get("Authorization");if(!auth?.startsWith("Bearer "))return null;const admin=createClient(SUPABASE_URL,SECRET_KEY,{auth:{autoRefreshToken:false,persistSession:false,detectSessionInUrl:false}});const{data:{user},error}=await admin.auth.getUser(auth.slice(7));if(error||!user)return null;const{data:profile}=await admin.from("profiles").select("id,role").eq("id",user.id).maybeSingle();return profile?.role==="teacher"?{user,admin}:null}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{headers:cors});try{const ctx=await teacherFromRequest(req);if(!ctx)return json({error:"teacher_required"},403);const body=await req.json();if(body.mode!=="import")return json({error:"unknown_mode"},400);const rows=Array.isArray(body.users)?body.users:[];if(!rows.length)return json({error:"no_users"},400);if(rows.length>500)return json({error:"too_many_users"},400);const results=[];for(const row of rows){const username=cleanUsername(row.username),password=String(row.password||""),full_name=String(row.full_name||username).trim();if(!/^[a-z0-9._-]{3,40}$/.test(username)||password.length<6){results.push({username,ok:false,error:"username must be 3-40 characters (letters, numbers, dot, underscore, hyphen) and password must be at least 6 characters"});continue}const email=emailForUsername(username);const{data:existing}=await ctx.admin.from("profiles").select("id").eq("username",username).maybeSingle();if(existing){results.push({username,ok:false,error:"username already exists"});continue}const{data:created,error}=await ctx.admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{username,full_name}});if(error||!created.user){results.push({username,ok:false,error:error?.message||"could not create user"});continue}const{error:profileError}=await ctx.admin.from("profiles").insert({id:created.user.id,email,username,full_name,role:"student"});if(profileError){await ctx.admin.auth.admin.deleteUser(created.user.id);results.push({username,ok:false,error:profileError.message});continue}results.push({username,ok:true})}return json({results,created:results.filter(x=>x.ok).length,failed:results.filter(x=>!x.ok).length})}catch(e){return json({error:"server_error",detail:String(e?.message||e)},500)}});