import { useState } from "react";
import { supabase } from "../lib/supabase";
import { markAnswer } from "../lib/aiRoute";
export default function MarkMyWork({session}) {
 const[answerFile,setAnswerFile]=useState(null),[answerText,setAnswerText]=useState(""),[schemeFile,setSchemeFile]=useState(null),[loading,setLoading]=useState(false),[result,setResult]=useState(null),[error,setError]=useState("");
 async function uploadPrivate(bucket,file){const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=session.user.id+"/"+crypto.randomUUID()+"-"+safeName;const{error}=await supabase.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;const{data,error:signError}=await supabase.storage.from(bucket).createSignedUrl(path,1800);if(signError)throw signError;return data.signedUrl}
 async function handleSubmit(){setError("");if(!session){setError("Sign in to mark your work.");return}if(!schemeFile){setError("A mark scheme is required alongside your answer.");return}if(!answerFile&&!answerText.trim()){setError("Attach a photo of your answer or type it in.");return}if(schemeFile.size>25*1024*1024){setError("Please keep the mark scheme below 25 MB.");return}setLoading(true);setResult(null);try{const markSchemeUrl=await uploadPrivate("mark-schemes",schemeFile);const answerImageUrl=answerFile?await uploadPrivate("answer-uploads",answerFile):undefined;const res=await markAnswer({answerText:answerText||undefined,answerImageUrl,markSchemeUrl,markSchemeMimeType:schemeFile.type});setResult(res);const r=res.result;const{error:saveError}=await supabase.from("paper_checks").insert({student_id:session.user.id,question_text:answerText||null,answer_image_url:answerImageUrl||null,mark_scheme_url:markSchemeUrl,mark_scheme_name:schemeFile.name,marks_awarded:r?.marks_awarded??null,marks_total:r?.marks_total??null,percentage:r?.percentage??null,grade:r?.grade??null,feedback:r?.feedback??null,model_used:res.modelUsed});if(saveError)throw saveError}catch(err){setError(err.message??"Something went wrong marking this.")}finally{setLoading(false)}}
 return <main className="container" style={styles.wrap}><div className="eyebrow">EXAM MARKER</div><h1 style={styles.h1}>Mark my work</h1><p style={styles.sub}>Upload your answer and the official mark scheme. The marker checks each mark-scheme point instead of guessing a grade.</p><div style={styles.form}><Field label="Your answer"><textarea style={styles.textarea} placeholder="Type your working, or attach a photo below" value={answerText} onChange={e=>setAnswerText(e.target.value)} rows={6}/><FilePicker file={answerFile} onChange={setAnswerFile} label="Attach photo of answer" accept="image/*"/></Field><Field label="Official mark scheme — required"><FilePicker file={schemeFile} onChange={setSchemeFile} label="Upload mark scheme (PDF or image)" accept="application/pdf,image/*" required/></Field>{error&&<p style={styles.error}>{error}</p>}<button style={styles.submit} onClick={handleSubmit} disabled={loading}>{loading?"Marking…":"Mark this answer"}</button></div>{result&&<ResultCard result={result}/>}</main>}
function Field({label,children}){return <div style={styles.field}><div style={styles.fieldLabel}>{label}</div>{children}</div>}
function FilePicker({file,onChange,label,accept,required}){return <label style={styles.filePicker}><input type="file" accept={accept} style={{display:"none"}} onChange={e=>onChange(e.target.files?.[0]??null)}/><span>{file?"✓ "+file.name:label}</span>{required&&!file&&<span style={styles.requiredTag}>required</span>}</label>}
function ResultCard({result}){const r=result.result;if(!r)return <div style={styles.resultCard}><p>Marked, but the model did not return structured results.</p><pre style={styles.rawPre}>{result.raw}</pre></div>;return <div style={styles.resultCard}><div style={styles.resultHeader}><div><div style={styles.scoreLine}>{r.marks_awarded} / {r.marks_total}</div><div style={styles.gradeLine}>Grade {r.grade}</div></div><div style={styles.percentCircle}>{r.percentage}%</div></div><div style={styles.feedbackList}>{(r.feedback??[]).map((f,i)=><div key={i} style={styles.feedbackItem}><span style={{color:f.awarded?"var(--green)":"var(--red)"}}>{f.awarded?"✓":"✗"}</span><div><div style={styles.feedbackPoint}>{f.point}</div><div style={styles.feedbackExplain}>{f.explanation}</div></div></div>)}</div><div style={styles.modelNote}>marked via {result.modelUsed}</div></div>}
const styles={wrap:{paddingTop:48,paddingBottom:72,maxWidth:680},h1:{fontSize:32},sub:{color:"#5a5748",marginTop:10,fontSize:15.5,maxWidth:"58ch"},form:{marginTop:32,background:"#fffefb",border:"1px solid var(--rule)",borderRadius:6,padding:24},field:{marginBottom:22},fieldLabel:{fontWeight:500,fontSize:14.5,marginBottom:8},textarea:{width:"100%",border:"1px solid var(--rule)",borderRadius:4,padding:12,fontSize:15,fontFamily:"var(--font-body)",resize:"vertical",marginBottom:8},filePicker:{display:"flex",alignItems:"center",justifyContent:"space-between",border:"1px dashed var(--rule)",borderRadius:4,padding:"11px 14px",fontSize:14,cursor:"pointer",color:"#4a4740"},requiredTag:{fontSize:11,color:"var(--red)",fontFamily:"var(--font-mono)"},error:{color:"var(--red)",fontSize:14,marginBottom:14},submit:{background:"var(--ink)",color:"var(--paper)",border:"none",borderRadius:4,padding:"13px 24px",fontSize:15,fontWeight:500},resultCard:{marginTop:28,background:"#fffefb",border:"1px solid var(--rule)",borderRadius:6,padding:24,boxShadow:"3px 4px 0 var(--rule)"},resultHeader:{display:"flex",justifyContent:"space-between",alignItems:"center",borderBottom:"1px dashed var(--rule)",paddingBottom:18,marginBottom:18},scoreLine:{fontFamily:"var(--font-display)",fontSize:28,fontWeight:600},gradeLine:{color:"var(--red)",fontWeight:500,marginTop:4},percentCircle:{width:56,height:56,borderRadius:"50%",border:"2px solid var(--amber)",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:600,fontSize:14},feedbackList:{display:"flex",flexDirection:"column",gap:14},feedbackItem:{display:"flex",gap:10,alignItems:"flex-start"},feedbackPoint:{fontWeight:500,fontSize:14.5},feedbackExplain:{fontSize:13.5,color:"#5a5748",marginTop:2},modelNote:{marginTop:18,fontSize:11.5,color:"#9a9684",fontFamily:"var(--font-mono)"},rawPre:{whiteSpace:"pre-wrap",fontSize:13}};
