import { useEffect, useRef, useState } from "react";
import { supabase } from "../lib/supabase";
import { askTutor } from "../lib/aiRoute";
import { useVoiceInput } from "../hooks/useVoiceInput";
const STORAGE_BUCKET="answer-uploads";
export default function Tutor({session}) {
  const [messages,setMessages]=useState([]),[input,setInput]=useState(""),[imageFile,setImageFile]=useState(null),[loading,setLoading]=useState(false),[modelUsed,setModelUsed]=useState(null),[conversationId,setConversationId]=useState(null);
  const fileRef=useRef(null); const voice=useVoiceInput();
  useEffect(()=>{let active=true;(async()=>{const{data}=await supabase.from("conversations").select("id,title,created_at,messages(id,role,content,model_used,input_type,image_url,audio_url,created_at)").eq("student_id",session.user.id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!active)return;if(data){setConversationId(data.id);setMessages((data.messages??[]).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)).map(({role,content})=>({role,content})))}})();return()=>{active=false}},[session.user.id]);
  async function ensureConversation(title){if(conversationId)return conversationId;const{data,error}=await supabase.from("conversations").insert({student_id:session.user.id,section:"tutor",unit_name:"physics",title:title?.slice(0,80)||"Physics question"}).select("id").single();if(error)throw error;setConversationId(data.id);return data.id}
  async function uploadPrivate(file,bucket=STORAGE_BUCKET){const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=session.user.id+"/"+crypto.randomUUID()+"-"+safeName;const{error}=await supabase.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;const{data,error:signError}=await supabase.storage.from(bucket).createSignedUrl(path,1800);if(signError)throw signError;return{path,url:data.signedUrl}}
  async function handleSend(){const text=input.trim();if(!text&&!imageFile&&!voice.audioBlob)return;setLoading(true);setInput("");try{let imageUrl,audioUrl,audioMimeType;if(imageFile){imageUrl=(await uploadPrivate(imageFile)).url;setImageFile(null)}if(voice.audioBlob){const audioFile=new File([voice.audioBlob],"voice-note.webm",{type:voice.audioBlob.type||"audio/webm"});audioUrl=(await uploadPrivate(audioFile,"voice-notes")).url;audioMimeType=audioFile.type;voice.clear()}const history=messages.map(({role,content})=>({role,content})).slice(-12);const inputLabel=audioUrl?"(voice note attached)":imageUrl?"(photo attached)":text;const userMsg={role:"user",content:text||inputLabel};setMessages(m=>[...m,userMsg]);const res=await askTutor({question:text,imageUrl,audioUrl,audioMimeType,conversationHistory:history});setModelUsed(res.modelUsed);setMessages(m=>[...m,{role:"assistant",content:res.answer}]);const cid=await ensureConversation(text||"Physics question");await supabase.from("messages").insert([{conversation_id:cid,role:"user",content:userMsg.content,input_type:audioUrl?"audio":imageUrl?"image":"text",image_url:imageUrl||null,audio_url:audioUrl||null},{conversation_id:cid,role:"assistant",content:res.answer,model_used:res.modelUsed,input_type:"text"}])}catch(err){setMessages(m=>[...m,{role:"assistant",content:"Couldn't get an answer right now ("+err.message+"). Try again in a moment."}])}finally{setLoading(false)}}
  return <main className="container" style={styles.wrap}><div className="eyebrow">PHYSICS TUTOR</div><h1 style={styles.h1}>Ask a question</h1><p style={styles.sub}>Type it, record a voice note, or attach a photo of your notes or textbook question.</p><div style={styles.thread}>{messages.length===0&&<div style={styles.empty}>Your conversation will appear here. Try a calculation, a concept question, or a photo of a diagram.</div>}{messages.map((m,i)=><div key={i} style={m.role==="user"?styles.userBubble:styles.assistantBubble}><div style={styles.bubbleLabel}>{m.role==="user"?"You":"Tutor"}</div><div style={styles.bubbleText}>{m.content}</div></div>)}{loading&&<div style={styles.empty}>Checking the question…</div>}</div>{modelUsed&&<div style={styles.modelNote}>answered via {modelUsed}</div>}<div style={styles.composer}>{imageFile&&<div style={styles.attachedFile}>📎 {imageFile.name}<button style={styles.removeAttach} onClick={()=>setImageFile(null)}>✕</button></div>}{voice.audioBlob&&<div style={styles.attachedFile}>🎙 Voice note ready <button style={styles.removeAttach} onClick={voice.clear}>✕</button></div>}<div style={styles.composerRow}><input style={styles.textInput} placeholder="Ask your physics question…" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&handleSend()}/><input ref={fileRef} type="file" accept="image/*" style={{display:"none"}} onChange={e=>setImageFile(e.target.files?.[0]??null)}/><button style={styles.iconBtn} onClick={()=>fileRef.current?.click()}>📷</button>{voice.supported&&<button style={{...styles.iconBtn,...(voice.listening?{background:"var(--red)",color:"white"}:{})}} onClick={voice.listening?voice.stop:voice.start}>{voice.listening?"■":"🎙"}</button>}<button style={styles.sendBtn} onClick={handleSend} disabled={loading}>Ask</button></div></div></main>}
const styles={wrap:{paddingTop:48,paddingBottom:64,maxWidth:760},h1:{fontSize:32},sub:{color:"#5a5748",marginTop:10,fontSize:15.5},thread:{marginTop:32,display:"flex",flexDirection:"column",gap:16,minHeight:200},empty:{color:"#8a8676",fontSize:14.5,fontStyle:"italic"},userBubble:{alignSelf:"flex-end",maxWidth:"80%",background:"var(--physics-blue)",color:"var(--paper)",borderRadius:"10px 10px 2px 10px",padding:"12px 16px"},assistantBubble:{alignSelf:"flex-start",maxWidth:"85%",background:"#fffefb",border:"1px solid var(--rule)",borderRadius:"10px 10px 10px 2px",padding:"12px 16px"},bubbleLabel:{fontSize:11,opacity:.7,marginBottom:4},bubbleText:{fontSize:15,lineHeight:1.55,whiteSpace:"pre-wrap"},modelNote:{marginTop:8,fontSize:11.5,color:"#9a9684",fontFamily:"var(--font-mono)"},composer:{marginTop:20,border:"1px solid var(--rule)",borderRadius:6,background:"#fffefb",padding:10},attachedFile:{display:"flex",alignItems:"center",gap:8,fontSize:13,padding:"4px 8px",marginBottom:6,color:"#5a5748"},removeAttach:{background:"none",border:"none",color:"var(--red)"},composerRow:{display:"flex",gap:8,alignItems:"center"},textInput:{flex:1,border:"none",padding:"10px 12px",fontSize:15.5,fontFamily:"var(--font-body)",outline:"none",background:"transparent"},iconBtn:{border:"1px solid var(--rule)",background:"var(--paper)",borderRadius:4,width:40,height:40,fontSize:16},sendBtn:{background:"var(--ink)",color:"var(--paper)",border:"none",borderRadius:4,padding:"10px 20px",fontWeight:500,fontSize:14.5}};
