import { createClient } from "jsr:@supabase/supabase-js@2";
const OPENROUTER_URL="https://openrouter.ai/api/v1/chat/completions";
const OPENROUTER_KEY=Deno.env.get("OPENROUTER_API_KEY");
const SUPABASE_URL=Deno.env.get("SUPABASE_URL");
const SERVICE_ROLE_KEY=(()=>{const legacy=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")?.trim();if(legacy)return legacy;try{return JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}").default?.trim()||null}catch{return null}})();
const CHAINS={text:["nvidia/nemotron-3-ultra-550b-a55b:free","qwen/qwen3.8-27b:free","nvidia/nemotron-3-super-120b-a12b:free","google/gemma-4-31b-it:free","poolside/laguna-s-2.1:free","inclusionai/ling-3.0-flash-sante:free","liquid/lfm-2.5-2.6b:free","cohere/north-mini-code:free","openrouter/free"],image:["qwen/qwen3.8-27b:free","google/gemma-4-31b-it:free","google/gemma-4-26b-a4b-it:free","nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free","thinkingmachines/inkling:free","thinkingmachines/inkling-small:free","openrouter/free"],audio:["nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free","thinkingmachines/inkling:free","thinkingmachines/inkling-small:free","openrouter/free"]};
const RECENT_FAILURE_WINDOW_MIN=10;
const SYSTEM_TUTOR="You are a precise IGCSE Physics tutor. Explain concepts clearly, show calculations with units, and do not invent information from an image or file. If something is unreadable, say exactly what is missing. Keep the answer student-friendly and focused.";
const SYSTEM_MARKER="You are an IGCSE Physics exam marker. The official mark scheme is the source of truth. Award only marks supported by the supplied scheme, including explicitly accepted alternatives. Never invent a mark-scheme point. If the student's answer or scheme is unreadable, report that limitation rather than guessing. Return ONLY valid JSON in this exact shape: {\"marks_awarded\":0,\"marks_total\":0,\"percentage\":0,\"grade\":\"\",\"feedback\":[{\"point\":\"\",\"awarded\":false,\"explanation\":\"\"}]}";
async function fetchAsDataUrl(url){const res=await fetch(url);if(!res.ok)throw new Error("file_fetch_failed:"+res.status);const contentType=(res.headers.get("content-type")||"application/octet-stream").split(";")[0];const bytes=new Uint8Array(await res.arrayBuffer());let binary="";for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));return{dataUrl:"data:"+contentType+";base64,"+btoa(binary),contentType};}
async function buildMessages(req){
 if(req.mode==="mark"){const content=[{type:"text",text:"Official mark scheme is attached below. Student answer is also attached below. Mark against the official scheme only.\n\nStudent typed answer:\n"+(req.answerText||"(no typed answer)")}];if(req.answerImageUrl){const a=await fetchAsDataUrl(req.answerImageUrl);content.push({type:"image_url",image_url:{url:a.dataUrl}})}if(req.markSchemeUrl){const s=await fetchAsDataUrl(req.markSchemeUrl);if((req.markSchemeMimeType||s.contentType).includes("pdf"))content.push({type:"file",file:{filename:"mark-scheme.pdf",file_data:s.dataUrl}});else content.push({type:"image_url",image_url:{url:s.dataUrl}})}return[{role:"system",content:SYSTEM_MARKER},{role:"user",content}]}
 const content=[];if(req.question)content.push({type:"text",text:req.question});if(req.imageUrl){const a=await fetchAsDataUrl(req.imageUrl);content.push({type:"image_url",image_url:{url:a.dataUrl}})}if(req.audioUrl){const a=await fetchAsDataUrl(req.audioUrl);const format=a.contentType.includes("wav")?"wav":a.contentType.includes("mpeg")||a.contentType.includes("mp3")?"mp3":"webm";content.push({type:"input_audio",input_audio:{data:a.dataUrl.split(",")[1],format}})}return[{role:"system",content:SYSTEM_TUTOR},...(req.conversationHistory||[]),{role:"user",content}];
}
async function getRecentlyFailedModels(supabase,modality){const since=new Date(Date.now()-RECENT_FAILURE_WINDOW_MIN*60000).toISOString();const{data}=await supabase.from("model_usage_log").select("model_id").eq("modality",modality).neq("status","ok").gte("created_at",since);return new Set((data||[]).map(r=>r.model_id))}
function logModelResult(supabase,model_id,modality,status){supabase.from("model_usage_log").insert({model_id,modality,status}).then(()=>{},()=>{})}
async function callModel(modelId,messages,mode){if(!OPENROUTER_KEY)throw Object.assign(new Error("OPENROUTER_API_KEY_missing"),{kind:"config"});const res=await fetch(OPENROUTER_URL,{method:"POST",headers:{Authorization:"Bearer "+OPENROUTER_KEY,"Content-Type":"application/json","HTTP-Referer":"https://physics-ai-sistant.netlify.app","X-Title":"Physics AI-sistant"},body:JSON.stringify({model:modelId,messages,max_tokens:mode==="mark"?2500:1800,temperature:mode==="mark"?0.1:0.4})});if(res.status===429)throw Object.assign(new Error("rate_limited"),{kind:"rate_limited"});if(!res.ok)throw Object.assign(new Error("model_error:"+res.status+":"+(await res.text()).slice(0,180)),{kind:"error"});const data=await res.json();const text=data?.choices?.[0]?.message?.content;if(!text?.trim())throw Object.assign(new Error("empty_response"),{kind:"error"});return text}
function safeParseMarkJson(text){try{const cleaned=text.replace(/\x60\x60\x60json|\x60\x60\x60/g,"").trim();const parsed=JSON.parse(cleaned);if(typeof parsed.marks_awarded!=="number"||typeof parsed.marks_total!=="number"||!Array.isArray(parsed.feedback))return null;return parsed}catch{return null}}
function corsHeaders(){return{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"}}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json",...corsHeaders()}})}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{headers:corsHeaders()});try{if(!SUPABASE_URL||!SERVICE_ROLE_KEY)return json({error:"supabase_config_missing"},500);const auth=req.headers.get("Authorization");if(!auth?.startsWith("Bearer "))return json({error:"unauthorized"},401);const userClient=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{global:{headers:{Authorization:auth}}});const{data:{user},error:userError}=await userClient.auth.getUser();if(userError||!user)return json({error:"unauthorized"},401);const body=await req.json();if(body.mode==="mark"&&!body.markSchemeUrl)return json({error:"mark_scheme_required"},400);const admin=createClient(SUPABASE_URL,SERVICE_ROLE_KEY);const chain=CHAINS[body.modality]||CHAINS.text;const failed=await getRecentlyFailedModels(admin,body.modality);const messages=await buildMessages(body);const ordered=[...chain.filter(m=>!failed.has(m)),...chain.filter(m=>failed.has(m))];let lastError;for(const modelId of ordered){try{const text=await callModel(modelId,messages,body.mode);logModelResult(admin,modelId,body.modality,"ok");if(body.mode==="mark"){const parsed=safeParseMarkJson(text);return json({modelUsed:modelId,result:parsed,raw:parsed?undefined:text})}return json({modelUsed:modelId,answer:text})}catch(e){const kind=e?.kind||"error";logModelResult(admin,modelId,body.modality,kind==="rate_limited"?"rate_limited":"error");lastError=e}}return json({error:"all_models_exhausted",detail:String(lastError?.message||lastError)},503)}catch(e){return json({error:"bad_request",detail:String(e?.message||e)},400)}});