-- Physics AI production hardening
alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.paper_checks enable row level security;
alter table public.model_usage_log enable row level security;
alter table public.materials enable row level security;
drop policy if exists "Authenticated can read all profiles" on public.profiles;
create policy "Authenticated can read profiles" on public.profiles for select to authenticated using (true);
drop policy if exists "Anyone authenticated can read materials" on public.materials;
create policy "Authenticated can read materials" on public.materials for select to authenticated using (true);
drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
drop policy if exists "Teachers can update own materials" on public.materials;
create policy "Teachers can update own materials" on public.materials for update to authenticated using ((select auth.uid()) = teacher_id) with check ((select auth.uid()) = teacher_id);
update storage.buckets set public=false where id in ('answer-uploads','answer-images','mark-schemes','voice-notes');
drop policy if exists "users manage own answer uploads" on storage.objects;
create policy "users manage own answer uploads" on storage.objects for all to authenticated using (bucket_id='answer-uploads' and (storage.foldername(name))[1]=(select auth.uid())::text) with check (bucket_id='answer-uploads' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists "users manage own mark schemes" on storage.objects;
create policy "users manage own mark schemes" on storage.objects for all to authenticated using (bucket_id='mark-schemes' and (storage.foldername(name))[1]=(select auth.uid())::text) with check (bucket_id='mark-schemes' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists "users manage own voice notes" on storage.objects;
create policy "users manage own voice notes" on storage.objects for all to authenticated using (bucket_id='voice-notes' and (storage.foldername(name))[1]=(select auth.uid())::text) with check (bucket_id='voice-notes' and (storage.foldername(name))[1]=(select auth.uid())::text);
update storage.buckets set file_size_limit=26214400, allowed_mime_types=array['image/png','image/jpeg','image/jpg']::text[] where id='answer-uploads';
update storage.buckets set file_size_limit=26214400, allowed_mime_types=array['application/pdf','image/png','image/jpeg','image/jpg']::text[] where id='mark-schemes';
update storage.buckets set file_size_limit=15728640, allowed_mime_types=array['audio/webm','audio/wav','audio/mpeg','audio/mp4','audio/ogg']::text[] where id='voice-notes';
create index if not exists conversations_student_created_idx on public.conversations(student_id, created_at desc);
create index if not exists messages_conversation_created_idx on public.messages(conversation_id, created_at);
create index if not exists paper_checks_student_created_idx on public.paper_checks(student_id, created_at desc);
create index if not exists model_usage_log_modality_created_idx on public.model_usage_log(modality, created_at desc);